serverUrl: http://syzoj-ng.test/
key: 40uXJPXzuO2Ha41iuh8Pjw1h0ahvP9i/zJk7Rtn/
dataStore: /root/judge/data
binaryCacheStore: /root/judge/cache
binaryCacheMaxSize: 536870912
taskConsumingThreads: 2
maxConcurrentDownloads: 10
maxConcurrentTasks: 3
taskWorkingDirectories:
  - /root/judge/1
  - /root/judge/2
  - /root/judge/3
sandbox:
  rootfs: /opt/sandbox-test/rootfs
  user: nobody
  hostname: null
  environments:
    - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - HOME=/tmp
limit:
  compilerMessage: 524288
  outputSize: 104857600
  dataDisplay: 128
  stderrDisplay: 5120
